image: registry.gitlab.com/mloldenburg/tvem

test:
  only:
    - master
    - merge_requests
  script:
    - source $SRC_CONDA
    - conda activate tvem
    - pytest
    - pylama --options .config/pylama.ini
    - mypy --ignore-missing-imports tvem
