variables:
   TVEM_GPU: 0

before_script:
    - source $SRC_CONDA
    - conda activate tvem

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - pylama --options .config/pylama.ini
    - mypy --ignore-missing-imports tvem test
    - pytest test

pages:
  stage: deploy
  only:
    - master
  script:
    - conda install -q -y -c conda-forge sphinx sphinx_rtd_theme sphinx-autodoc-typehints
    - sphinx-build docs public
  artifacts:
    paths:
      - public
