# Configuration to run TVEM CI on our workstations
# It assumes conda is installed, in path, and the tvem environment has been created from our repo's env.yml file.
# The special environment python/3.6.4-ompi (pytorch+CUDA+MPI) is loaded to run parallelization tests.
# Documentation generation with sphinx additionally requires
# `conda install -c conda-forge sphinx sphinx_rtd_theme sphinx-autodoc-typehints`

before_script:
    - source /home/gitlab-runner/anaconda3/etc/profile.d/conda.sh
    - conda activate tvem

test:
  stage: test
  only:
     - master
     - merge_requests
  script:
    # static checkers
    - black --check -q . || { black --diff -q . && false; }
    - pylama --options .config/pylama.ini
    - mypy --ignore-missing-imports tvem test
    # CPU tests
    - pytest --cov=tvem -v test
    # GPU tests
    - env TVEM_GPU=0 pytest --cov=tvem --cov-append -v -m gpu test
    # mpi tests
    - module load python/3.6.4-ompi
    - mpirun -n 4 bash .ci_scripts/run_mpi_tests.sh 0 # coverage of rank 0
    - mpirun -n 4 bash .ci_scripts/run_mpi_tests.sh 1 # coverage of rank 1
  artifacts:
    paths:
      - .coverage

pages:
  stage: deploy
  only:
    - master
  script:
    - sphinx-build docs public
    - python .ci_scripts/make_coverage_badge.py public/cov_badge.svg
    - python .ci_scripts/make_coverage_html_report.py public/htmlcov
  artifacts:
    paths:
      - public
