# Configuration to run TVEM CI on our workstations
# It assumes conda is installed, in path, and the tvem environment has been created from our repo's environment.yml file.
# The special environment python/3.6.4-ompi (pytorch+CUDA+MPI) is loaded to run parallelization tests.
# Documentation generation with sphinx additionally requires
# `conda install -c conda-forge sphinx sphinx_rtd_theme sphinx-autodoc-typehints`

# FIXME switch back when we go back to self-hosted runners
image: registry.gitlab.com/mloldenburg/tvem
before_script:
    - source /opt/conda/etc/profile.d/conda.sh
    - conda activate tvem

test:
  stage: test
  only:
     - master
     - tags
     - merge_requests
  script:
    # static checkers
    - black --check -q . || { black --diff -q . && false; }
    - pylama
    - mypy tvem test
    # compile extension modules
    - python setup.py build_ext --inplace
    # CPU tests
    - pytest --cov=tvem -v test
    # GPU tests
    # FIXME: re-enable when we go back to self-hosted runners
    #- env TVEM_GPU=0 pytest --cov=tvem --cov-append -v -m gpu test
    # mpi tests (force a timeout because mpi might hang in case of python runtime errors)
    # FIXME: re-enable when we have a working pytorch+MPI environment
    # - module load python/3.6.4-ompi
    # - timeout 5m mpirun -n 4 bash .ci_scripts/run_mpi_tests.sh 0 # coverage of rank 0
    # - timeout 5m mpirun -n 4 bash .ci_scripts/run_mpi_tests.sh 3 # coverage of rank 3
  artifacts:
    paths:
      - .coverage

conda:
  stage: deploy
  only:
    - tags
  script:
    - anaconda login --username $ANACONDA_USER --password $ANACONDA_PASSWORD
    - conda build -c pytorch -c conda-forge .
    - anaconda upload -u mloldenburg $(conda build --output .)
    - anaconda logout

pages:
  stage: deploy
  only:
    - master
    - tags
  script:
    - python setup.py build_ext --inplace
    - sphinx-build docs public
    - python .ci_scripts/make_coverage_badge.py public/cov_badge.svg
    - python .ci_scripts/make_coverage_html_report.py public/htmlcov
  artifacts:
    paths:
      - public
