image: bluehood/tvem

definitions:
  steps:
    - step: &test
        name: test
        script:
          - conda activate tvem
          - pytest
          - pylama --options .config/pylama.ini
          - mypy --ignore-missing-imports tvem

pipelines:
  branches:
    master:
      - step: *test
  pull-requests:
    '**':
      - step: *test
