name: tvo
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pytorch>=1.8.1
  - torchvision
  - cudatoolkit>=10.0
  - matplotlib
  - h5py
  - pylama
  - pyflakes=2.4.0
  - pytest
  - mypy
  - pytest-cov
  - black>=21
  - munch
  - cython
  - gcc_linux-64
