package:
  name: tvem
  version: 0.5

about:
  home: https://gitlab.com/mloldenburg/tvem
  license: Academic Free License v3.0
  license_file: LICENSE
  summary: Library for truncated variational expectation maximization
  doc_url: https://mloldenburg.gitlab.io/tvem
  description: |
   Library for truncated variational expectation maximization.
   Install with `conda install -c conda-forge -c pytorch -c mloldenburg tvem`

source:
  path: .

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
  run:
    - python=3
    - numpy
    - pytorch=1
    - torchvision
    - cudatoolkit=10.0
    - matplotlib
    - h5py
    - munch

test:
  imports:
    - tvem
